// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvfnqnWSHeEeBIqsZN7E0OzccfHBZL14',
    appId: '1:26689362584:web:c682413bdda3ad57bb0eed',
    messagingSenderId: '26689362584',
    projectId: 'misscreps-d2687',
    authDomain: 'misscreps-d2687.firebaseapp.com',
    storageBucket: 'misscreps-d2687.appspot.com',
    measurementId: 'G-1RHPE05G1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlbyoebOG2j-Cckb1jtABr_1d88yZkWI',
    appId: '1:26689362584:android:669b5206a4e6ecdabb0eed',
    messagingSenderId: '26689362584',
    projectId: 'misscreps-d2687',
    storageBucket: 'misscreps-d2687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-HHpsoeIxzkRDqr_b5hTlsN0cYeO1Z4',
    appId: '1:26689362584:ios:c36717c48c36c474bb0eed',
    messagingSenderId: '26689362584',
    projectId: 'misscreps-d2687',
    storageBucket: 'misscreps-d2687.appspot.com',
    iosBundleId: 'com.example.appCrepas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-HHpsoeIxzkRDqr_b5hTlsN0cYeO1Z4',
    appId: '1:26689362584:ios:a60030c75b88399fbb0eed',
    messagingSenderId: '26689362584',
    projectId: 'misscreps-d2687',
    storageBucket: 'misscreps-d2687.appspot.com',
    iosBundleId: 'com.example.appCrepas.RunnerTests',
  );
}
